version: "3.1"

services:

  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5433
    networks:
      - dev

  keycloakserver:
    image: quay.io/keycloak/keycloak:20.0
    command: ["start-dev", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Dkeycloak.migration.file=/opt/keycloak/data/import/master.json"]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    networks:
      - dev

volumes:
  pg_data:

networks: # Optional, same as docker network create
  dev:
    driver: bridge
